### ISSUE TITLE
a not building....

### ISSUE THREAD

**Issue by xt0fer** [as/a#134]
Trying a build on Mac OSX 10.13.3; go version go1.10 darwin/amd64

$ go get -u -t github.com/as/a
# github.com/as/ms/win
GitHub/go/src/github.com/as/ms/win/win.go:10:12: undefined: Open
GitHub/go/src/github.com/as/ms/win/win.go:25:12: undefined: Open
GitHub/go/src/github.com/as/ms/win/win.go:53:2: not enough arguments to return
	have ([]uintptr)
	want ([]uintptr, error)
# github.com/as/shiny/driver/gldriver
cocoa.m:24:5: error: redefinition of enumerator 'NSEventTypeScrollWheel'
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:40:5: note: previous definition is here
cocoa.m:25:5: error: redefinition of enumerator 'NSEventTypeKeyDown'
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:32:5: note: previous definition is here
cocoa.m:28:5: error: redefinition of enumerator 'NSWindowStyleMaskTitled'
/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:36:5: note: previous definition is here
cocoa.m:29:5: error: redefinition of enumerator 'NSWindowStyleMaskResizable'
/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:39:5: note: previous definition is here
cocoa.m:30:5: error: redefinition of enumerator 'NSWindowStyleMaskMiniaturizable'
/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:38:5: note: previous definition is here
cocoa.m:31:5: error: redefinition of enumerator 'NSWindowStyleMaskClosable'
/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:37:5: note: previous definition is here

ain't that peculiar.

**Comment by kristofer** [comment]
so maybe it no run on MacOS?

**Comment by as** [comment]
>github.com/as/ms/win
The bug here is clear

>github.com/as/shiny/driver/gldriver
That one isn't as obvious. The master branch ran on `darwin` a few weeks ago, on macOS sierra. Which version of `macOS` are you building on?

**Comment by kristofer** [comment]
high sierra. most likely the very latest.
